codecov:
  max_report_age: off
  notify:
    after_n_builds: 1
    require_ci_to_pass: no    

coverage:
  status:
    project:
      default:
        threshold: 50%
    patch:
      default:
        threshold: 50%
  ignore:
   - "tests/"
   - "psi4/driver/qcdb/"
   - "psi4/share/"
