# Configure LGTM for this package

extraction:
  python:
    python_setup:
      version: 3
  cpp:
    prepare:
      packages:
        - python3-pint
        - python3-numpy
path_classifiers:
  library:
    - psi4/versioner.py
    - samples/*
    - conda/*
