# Configure LGTM for this package

extraction:
  python:
    python_setup:
      version: 3
  cpp:
    prepare:
      packages:
        - python3-pint
        - python3-numpy
  javascript:
    index:
      filters:
        - exclude: "tests/pytests/*.json"
path_classifiers:
  library:
    - psi4/versioner.py
    - samples/*
    - conda/*
    - devtools/*
    - codemeta.json
