[tool.pytest.ini_options]
markers = [
    "check_triplet",
    "dft",
    "gga",
    "hf",
    "hyb_gga",
    "hyb_gga_lrc",
    "lda",
    "long",
    "mdi",
    "mp2",
    "restricted_singlet",
    "restricted_triplet",
    "RPA",
    "scf",
    """slow: marks tests as slow (deselect with '-m "not slow"')""",
    "smoke",
    "solver",
    "stress",
    "TDA",
    "tdscf",
    "quick",
    "unittest",
    "unrestricted",
]
python_path = [
    "tests/pytests",
]

