include $(top_objdir)/src/lib/MakeVars
include $(top_objdir)/src/lib/libr12/MakeVars

LD = $(CC)
LDFLAGS += -lm
vpath %.a $(libdir)

BINOBJ = $(BUILD_SRC:%.c=%.o)

$(BUILD_BINARY): $(BINOBJ) $(LDLIBS)
	$(LD) $^ $(LDFLAGS) -o $@

%.$(OBJSUF): %.c
	$(CC) $(CFLAGS) -c $< $(OUTPUT_OPTION)

