# Do not modify this file! It is auto-generated by the document_options_and_tests
# script, from psi4topdir/include/physconst.h
_h                        = 6.6260755E-34        # The Planck constant (Js)               
_c                        = 2.99792458E8         # Speed of light (ms$^{-1}$)             
_kb                       = 1.380658E-23         # The Boltzmann constant (JK$^{-1}$      
_R                        = 8.314510             # Universal gas constant (JK$^{-1}$mol$^{-1}$ 
_bohr2angstroms           = 0.529177249          # Bohr to Angstroms conversion factor    
_bohr2m                   = 0.529177249E-10      # Bohr to meters conversion factor       
_bohr2cm                  = 0.529177249E-8       # Bohr to centimeters conversion factor  
_amu2g                    = 1.6605402E-24        # Atomic mass units to grams conversion factor 
_amu2kg                   = 1.6605402E-27        # Atomic mass units to kg conversion factor 
_au2amu                   = 5.485799110E-4       # Atomic units (m$@@e$) to atomic mass units conversion factor 
_hartree2J                = 4.35974381E-18       # Hartree to joule conversion factor     
_hartree2aJ               = 4.35974381           # Hartree to attojoule (10$^{-18}$J) conversion factor 
_cal2J                    = 4.184                # Calorie to joule conversion factor     
_dipmom_au2si             = 8.47835791E-30       # Atomic units to SI units (Cm) conversion factor for dipole moments 
_dipmom_au2debye          = 2.54175              # Atomic units to Debye conversion factor for dipole moments 
_dipmom_debye2si          = 3.33564E-30          # Debye to SI units (Cm) conversion factor for dipole moments 
_c_au                     = 137.0359895          # Speed of light in atomic units         
_hartree2ev               = 27.211396            # Hartree to eV conversion factor        
_hartree2wavenumbers      = 219474.6313710       # Hartree to cm$^{-1}$ conversion factor 
_e0                       = 8.854187816E-12      # Vacuum permittivity                    
_na                       = 6.022136736E23       # Avagadro's number                      
_me                       = 9.10938188E-31       # Electron rest mass                     
