#ifndef FT97_C_MATLAB_FUNCTIONAL_H
#define FT97_C_MATLAB_FUNCTIONAL_H

#include "functional.h"

namespace psi {

/** 
 * FT97_C MATLAB Autogenerated functional 
 **/

class FT97_CFunctional : public Functional {

public:

    FT97_CFunctional();
    virtual ~FT97_CFunctional(); 
    virtual void compute_functional(const std::map<std::string,SharedVector>& in, const std::map<std::string,SharedVector>& out, int npoints, int deriv, double alpha);

};

}

#endif
