#ifndef FT97B_X_MATLAB_FUNCTIONAL_H
#define FT97B_X_MATLAB_FUNCTIONAL_H

#include "functional.h"

namespace psi {

/** 
 * FT97B_X MATLAB Autogenerated functional 
 **/

class FT97B_XFunctional : public Functional {

public:

    FT97B_XFunctional();
    virtual ~FT97B_XFunctional(); 
    virtual void compute_functional(const std::map<std::string,SharedVector>& in, const std::map<std::string,SharedVector>& out, int npoints, int deriv, double alpha);

};

}

#endif
