#ifndef HCTH_functional_h
#define HCTH_functional_h
/**********************************************************
* HCTH_functional.h: declarations for HCTH_functional for KS-DFT
* Robert Parrish, robparrish@gmail.com
* Autogenerated by MATLAB Script on 27-Oct-2010
*
***********************************************************/
#include <libmints/properties.h>
#include <libciomr/libciomr.h>
#include "functional.h"
#include <stdlib.h>
#include <string>
#include <vector>

using namespace psi;
using namespace boost;
using namespace std;

namespace psi { namespace functional {

class HCTH_Functional : public Functional {
public:
    HCTH_Functional(int npoints, int deriv);
    virtual ~HCTH_Functional();
    virtual void computeRKSFunctional(shared_ptr<Properties> prop);
    virtual void computeUKSFunctional(shared_ptr<Properties> prop);
};
}}
#endif

