#ifndef PBE_C_MATLAB_FUNCTIONAL_H
#define PBE_C_MATLAB_FUNCTIONAL_H

#include "functional.h"

namespace psi {

/** 
 * PBE_C MATLAB Autogenerated functional 
 **/

class PBE_CFunctional : public Functional {

public:

    PBE_CFunctional();
    virtual ~PBE_CFunctional(); 
    virtual void compute_functional(const std::map<std::string,SharedVector>& in, const std::map<std::string,SharedVector>& out, int npoints, int deriv, double alpha);

};

}

#endif
