{ "run_type",        "sp",               parse_run_type,  NULL,           offsetof(struct config, run_type)           },
{ "coord",           "xyzabc",           parse_coord,     NULL,           offsetof(struct config, coord_type)         },
{ "terms",           "elec pol disp xr", parse_terms,     NULL,           offsetof(struct config, terms)              },
{ "elec_damp",       "screen",           parse_elec_damp, NULL,           offsetof(struct config, elec_damp)          },
{ "disp_damp",       "tt",               parse_disp_damp, NULL,           offsetof(struct config, disp_damp)          },
{ "pol_damp",        "tt",               parse_pol_damp,  NULL,           offsetof(struct config, pol_damp)           },
{ "enable_cutoff",   "false",            parse_bool,      NULL,           offsetof(struct config, enable_cutoff)      },
{ "swf_cutoff",      "10.0",             parse_double,    NULL,           offsetof(struct config, swf_cutoff)         },
{ "max_steps",       "100",              parse_int,       int_gt_zero,    offsetof(struct config, max_steps)          },
{ "fraglib_path",    FRAGLIB_PATH,       parse_string,    NULL,           offsetof(struct config, fraglib_path)       },
{ "userlib_path",    ".",                parse_string,    NULL,           offsetof(struct config, userlib_path)       },
{ "enable_pbc",      "false",            parse_bool,      NULL,           offsetof(struct config, enable_pbc)         },
{ "periodic_box",    "30.0 30.0 30.0",   parse_vec,       NULL,           offsetof(struct config, box)                },
{ "opt_tol",         "0.0001",           parse_double,    double_gt_zero, offsetof(struct config, opt_tol)            },
{ "hess_central",    "false",            parse_bool,      NULL,           offsetof(struct config, hess_central)       },
{ "hess_step_dist",  "0.001",            parse_double,    double_gt_zero, offsetof(struct config, hess_step_dist)     },
{ "hess_step_angle", "0.01",             parse_double,    double_gt_zero, offsetof(struct config, hess_step_angle)    },
{ "ensemble",        "nve",              parse_ensemble,  NULL,           offsetof(struct config, ensemble_type)      },
{ "time_step",       "1.0",              parse_double,    double_gt_zero, offsetof(struct config, time_step)          },
{ "print_step",      "1",                parse_int,       int_gt_zero,    offsetof(struct config, print_step)         },
{ "velocitize",      "false",            parse_bool,      NULL,           offsetof(struct config, velocitize)         },
{ "temperature",     "300.0",            parse_double,    double_gt_zero, offsetof(struct config, target_temperature) },
{ "pressure",        "1.0",              parse_double,    double_gt_zero, offsetof(struct config, target_pressure)    },
{ "thermostat_tau",  "1000.0",           parse_double,    double_gt_zero, offsetof(struct config, thermostat_tau)     },
{ "barostat_tau",    "10000.0",          parse_double,    double_gt_zero, offsetof(struct config, barostat_tau)       }
