# frozen_string_literal: true
source "https://rubygems.org"

gem "danger"
gem 'danger-code_style_validation', :git => 'https://github.com/robertodr/danger-code_style_validation.git', :branch => 'pass-exe'
