include(SaveCompilerFlags)
include(CheckCXX11Features)
include(CheckCXXCompilerFlag)
include(CheckCCompilerFlag)
include(CheckFortranCompilerFlag)
include(TestRestrict)

if(ENABLE_VECTORIZATION)
   include(FindBrokenIntrinsics)
   include(OptimizeForArchitecture)
   set(DEFINITIONS)
   set(CXX_ARCHITECTURE_FLAGS)
   set(C_ARCHITECTURE_FLAGS)
   set(Fortran_ARCHITECTURE_FLAGS)
   find_broken_intrinsics()
   OptimizeForArchitecture()
   message(STATUS "Vectorization flags set:")
   message(STATUS "  CXX    : ${CXX_ARCHITECTURE_FLAGS}")
   message(STATUS "  C      : ${C_ARCHITECTURE_FLAGS}")
   message(STATUS "  Fortran: ${Fortran_ARCHITECTURE_FLAGS}")
endif()	

test_restrict(restrict)
set(RESTRICT ${restrict})

if(CMAKE_C_COMPILER_WORKS)
    include(CFlags)
endif()

if(CMAKE_CXX_COMPILER_WORKS)
    include(CXXFlags)
endif()

if(CMAKE_Fortran_COMPILER_WORKS)
    include(FortranFlags)
endif()
