if(NOT DEFINED DEFUALT_CXX_FLAGS_SET OR RESET_FLAGS)
  if(CMAKE_CXX_COMPILER_ID MATCHES GNU)
      set(CMAKE_CXX_FLAGS "-DRESTRICT=${restrict_keyword}")
      if(HAS_CXX11_SUPPORT)
	      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC ${CXX11_COMPILER_FLAGS}")
      else()
	      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC -std=gnu++98")
      endif()
      set(CMAKE_CXX_FLAGS_DEBUG   "-O0 -g3 -DDEBUG -Wall -Wextra -Winit-self -Woverloaded-virtual -Wuninitialized -Wmissing-declarations -Wwrite-strings")
      set(CMAKE_CXX_FLAGS_RELEASE "-O3 -DNDEBUG -Wno-unused")
      if(ENABLE_VECTORIZATION)
	      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${CXX_ARCHITECTURE_FLAGS} ${DEFINITIONS}")
      endif()	      
      if(ENABLE_CODE_COVERAGE)
          set(CMAKE_CXX_FLAGS      "${CMAKE_CXX_FLAGS} -fprofile-arcs -ftest-coverage")
	  set(CMAKE_CXX_LINK_FLAGS "${CMAKE_CXX_LINK_FLAGS} -fprofile-arcs -ftest-coverage")
      endif()	  
  endif()

  if(CMAKE_CXX_COMPILER_ID MATCHES Intel)
      set(CMAKE_CXX_FLAGS "-DRESTRICT=${restrict_keyword}")
      if(HAS_CXX11_SUPPORT)
	      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC ${CXX11_COMPILER_FLAGS}")
      else()
	      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC -std=gnu++98")
      endif()
      set(CMAKE_CXX_FLAGS_DEBUG   "${CMAKE_CXX_FLAGS_DEBUG} -O0 -debug -DDEBUG -Wall -Wuninitialized -Wno-unknown-pragmas") # -Weffc++")
      set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O3 -DNDEBUG")
      set(CMAKE_CXX_LINK_FLAGS    "${CMAKE_CXX_LINK_FLAGS} -shared-intel")
      if(ENABLE_VECTORIZATION)
	      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${CXX_ARCHITECTURE_FLAGS} ${DEFINITIONS}")
      endif()	      
  endif()
  
  if(CMAKE_CXX_COMPILER_ID MATCHES Clang)
      set(CMAKE_CXX_FLAGS "-DRESTRICT=${restrict_keyword}")
      if(HAS_CXX11_SUPPORT)
	      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC ${CXX11_COMPILER_FLAGS}")
      else()
	      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC -std=gnu++98")
      endif()
      set(CMAKE_CXX_FLAGS_DEBUG    "-O0 -g -DDEBUG -Wall -Wextra -Winit-self -Woverloaded-virtual -Wuninitialized -Wmissing-declarations -Wwrite-strings -Weffc++ -Wdocumentation")
      set(CMAKE_CXX_FLAGS_RELEASE  "-O3 -DNDEBUG -Wno-unused")
      if(ENABLE_VECTORIZATION)
	      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${CXX_ARCHITECTURE_FLAGS} ${DEFINITIONS}")
      endif()	      
  endif()

  save_compiler_flags(CXX)

endif ()
