libcomex_la_SOURCES += src-portals4/comex.c
libcomex_la_SOURCES += src-portals4/comex_impl.h
libcomex_la_SOURCES += src-portals4/groups.c
libcomex_la_SOURCES += src-portals4/groups.h

AM_CPPFLAGS += -I$(top_srcdir)/src-portals4
