#ifndef NAME_MATLAB_FUNCTIONAL_H
#define NAME_MATLAB_FUNCTIONAL_H

#include "functional.h"

namespace psi {

/** 
 * NAME MATLAB Autogenerated functional 
 **/

class NAMEFunctional : public Functional {

public:

    NAMEFunctional();
    virtual ~NAMEFunctional(); 
    virtual void compute_functional(const std::map<std::string,SharedVector>& in, const std::map<std::string,SharedVector>& out, int npoints, int deriv, double alpha);

};

}

#endif
