.TH MA_INITIALIZED 3 "20 February 1997" "MA Release 1.8" "MA LIBRARY ROUTINES"
.SH NAME
MA_initialized -
find out if MA has been successfully initialized
.SH "C SYNOPSIS"
.nf
#include "macdecls.h"

Boolean MA_initialized()
.fi
.SH "FORTRAN SYNOPSIS"
.nf
#include "mafdecls.fh"

logical function MA_initialized()
.fi
.SH DESCRIPTION
MA_initialized() returns true
if MA_init() has been called successfully,
otherwise it returns false.
.\" .SH USAGE
.\" .SH DIAGNOSTICS
.SH "RETURN VALUE"
C: MA_TRUE if MA has been successfully initialized, MA_FALSE otherwise.
.br
FORTRAN: .true. if MA has been successfully initialized, .false. otherwise.
.\" .SH NOTES
.SH FILES
.nf
Include files: /msrc/proj/hpctools/ma/release/current/include
Library:       /msrc/proj/hpctools/ma/release/current/lib/\fIplatform\fR/libma.a
Man pages:     /msrc/proj/hpctools/ma/release/current/man/man3
Source code:   /msrc/proj/hpctools/ma/release/current/tar/ma\fIrelease\fR.tar
.fi
.SH "SEE ALSO"
.na
MA(3),
MA_init(3)
.ad
.SH AUTHOR
Gregory S. Thomas, Pacific Northwest National Laboratory
