.TH MA_INITIALIZE_MEMHANDLE_ITERATOR 3 "20 February 1997" "MA Release 1.8" " "
.SH NAME
MA_init_memhandle_iterator -
initialize a scan of currently allocated blocks
.SH "C SYNOPSIS"
.nf
#include "macdecls.h"

Boolean MA_init_memhandle_iterator(ithandle)
    Integer     *ithandle;      /* write-only */
.fi
.SH "FORTRAN SYNOPSIS"
.nf
#include "mafdecls.fh"

logical function MA_init_memhandle_iterator(ithandle)
    integer     ithandle
.fi
.SH DESCRIPTION
MA_init_memhandle_iterator() returns in
.I ithandle
the iterator handle for a scan of currently allocated blocks.
.SH USAGE
The following FORTRAN code illustrates the use of MA_init_memhandle_iterator()
by looping over all currently allocated blocks.

.nf
#include "mafdecls.fh"

    logical ok
    integer ihandle
    integer mhandle

    ok = MA_init_memhandle_iterator(ihandle)
    if (ok) then
        ok = MA_get_next_memhandle(ihandle, mhandle)
10      if (ok) then
            ... process mhandle
            ok = MA_get_next_memhandle(ihandle, mhandle)
            goto 10
        endif
    endif
.fi
.\" .SH DIAGNOSTICS
.SH "RETURN VALUE"
C: MA_TRUE upon success, MA_FALSE upon failure.
.br
FORTRAN: .true. upon success, .false. upon failure.
.SH NOTES
This routine is not yet implemented.
.SH FILES
.nf
Include files: /msrc/proj/hpctools/ma/release/current/include
Library:       /msrc/proj/hpctools/ma/release/current/lib/\fIplatform\fR/libma.a
Man pages:     /msrc/proj/hpctools/ma/release/current/man/man3
Source code:   /msrc/proj/hpctools/ma/release/current/tar/ma\fIrelease\fR.tar
.fi
.SH "SEE ALSO"
.na
MA(3),
MA_get_next_memhandle(3)
.ad
.SH AUTHOR
Gregory S. Thomas, Pacific Northwest National Laboratory
