.TH MA_SET_AUTO_VERIFY 3 "20 February 1997" "MA Release 1.8" "MA LIBRARY ROUTINES"
.SH NAME
MA_set_auto_verify -
set the ma_auto_verify flag
.SH "C SYNOPSIS"
.nf
#include "macdecls.h"

Boolean MA_set_auto_verify(value)
    Boolean     value;          /* read-only */
.fi
.SH "FORTRAN SYNOPSIS"
.nf
#include "mafdecls.fh"

logical function MA_set_auto_verify(value)
    logical     value
.fi
.SH DESCRIPTION
MA_set_auto_verify() sets the ma_auto_verify flag to
.I value
and returns the flag's previous value.
If the ma_auto_verify flag is true,
then MA_verify_allocator_stuff() is called
upon invocation
by every other public MA routine
except:

.in +0.5i
.nf
MA_initialized()
MA_set_auto_verify()
MA_set_error_print()
MA_set_hard_fail()
.fi
.in

The ma_auto_verify flag is initially false.
.\" .SH USAGE
.\" .SH DIAGNOSTICS
.SH "RETURN VALUE"
C: The previous value of the ma_auto_verify flag
(MA_TRUE or MA_FALSE).
.br
FORTRAN: The previous value of the ma_auto_verify flag
(.true. or .false.).
.\" .SH NOTES
.SH FILES
.nf
Include files: /msrc/proj/hpctools/ma/release/current/include
Library:       /msrc/proj/hpctools/ma/release/current/lib/\fIplatform\fR/libma.a
Man pages:     /msrc/proj/hpctools/ma/release/current/man/man3
Source code:   /msrc/proj/hpctools/ma/release/current/tar/ma\fIrelease\fR.tar
.fi
.SH "SEE ALSO"
.na
MA(3),
MA_set_error_print(3),
MA_set_hard_fail(3),
MA_verify_allocator_stuff(3)
.ad
.SH AUTHOR
Gregory S. Thomas, Pacific Northwest National Laboratory
