void deriv_build_AX_0(prim_data *, const int, double *, const double *, const double *);
void deriv_build_AY_0(prim_data *, const int, double *, const double *, const double *);
void deriv_build_AZ_0(prim_data *, const int, double *, const double *, const double *);
void deriv_build_BX_0(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_BY_0(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_BZ_0(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_CX_0(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_CY_0(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_CZ_0(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_DX_0(prim_data *, const int, double *, const double *, const double *);
void deriv_build_DY_0(prim_data *, const int, double *, const double *, const double *);
void deriv_build_DZ_0(prim_data *, const int, double *, const double *, const double *);
void deriv_build_AX_p(prim_data *, const int, double *, const double *, const double *);
void deriv_build_AY_p(prim_data *, const int, double *, const double *, const double *);
void deriv_build_AZ_p(prim_data *, const int, double *, const double *, const double *);
void deriv_build_BX_p(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_BY_p(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_BZ_p(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_CX_p(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_CY_p(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_CZ_p(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_DX_p(prim_data *, const int, double *, const double *, const double *);
void deriv_build_DY_p(prim_data *, const int, double *, const double *, const double *);
void deriv_build_DZ_p(prim_data *, const int, double *, const double *, const double *);
void deriv_build_AX_d(prim_data *, const int, double *, const double *, const double *);
void deriv_build_AY_d(prim_data *, const int, double *, const double *, const double *);
void deriv_build_AZ_d(prim_data *, const int, double *, const double *, const double *);
void deriv_build_BX_d(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_BY_d(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_BZ_d(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_CX_d(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_CY_d(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_CZ_d(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_DX_d(prim_data *, const int, double *, const double *, const double *);
void deriv_build_DY_d(prim_data *, const int, double *, const double *, const double *);
void deriv_build_DZ_d(prim_data *, const int, double *, const double *, const double *);
void deriv_build_AX_f(prim_data *, const int, double *, const double *, const double *);
void deriv_build_AY_f(prim_data *, const int, double *, const double *, const double *);
void deriv_build_AZ_f(prim_data *, const int, double *, const double *, const double *);
void deriv_build_BX_f(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_BY_f(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_BZ_f(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_CX_f(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_CY_f(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_CZ_f(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_DX_f(prim_data *, const int, double *, const double *, const double *);
void deriv_build_DY_f(prim_data *, const int, double *, const double *, const double *);
void deriv_build_DZ_f(prim_data *, const int, double *, const double *, const double *);
void deriv_build_AX_g(prim_data *, const int, double *, const double *, const double *);
void deriv_build_AY_g(prim_data *, const int, double *, const double *, const double *);
void deriv_build_AZ_g(prim_data *, const int, double *, const double *, const double *);
void deriv_build_BX_g(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_BY_g(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_BZ_g(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_CX_g(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_CY_g(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_CZ_g(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_DX_g(prim_data *, const int, double *, const double *, const double *);
void deriv_build_DY_g(prim_data *, const int, double *, const double *, const double *);
void deriv_build_DZ_g(prim_data *, const int, double *, const double *, const double *);
void deriv_build_AX_h(prim_data *, const int, double *, const double *, const double *);
void deriv_build_AY_h(prim_data *, const int, double *, const double *, const double *);
void deriv_build_AZ_h(prim_data *, const int, double *, const double *, const double *);
void deriv_build_BX_h(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_BY_h(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_BZ_h(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_CX_h(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_CY_h(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_CZ_h(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_DX_h(prim_data *, const int, double *, const double *, const double *);
void deriv_build_DY_h(prim_data *, const int, double *, const double *, const double *);
void deriv_build_DZ_h(prim_data *, const int, double *, const double *, const double *);
void deriv_build_AX_i(prim_data *, const int, double *, const double *, const double *);
void deriv_build_AY_i(prim_data *, const int, double *, const double *, const double *);
void deriv_build_AZ_i(prim_data *, const int, double *, const double *, const double *);
void deriv_build_BX_i(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_BY_i(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_BZ_i(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_CX_i(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_CY_i(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_CZ_i(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_DX_i(prim_data *, const int, double *, const double *, const double *);
void deriv_build_DY_i(prim_data *, const int, double *, const double *, const double *);
void deriv_build_DZ_i(prim_data *, const int, double *, const double *, const double *);
void deriv_build_AX_k(prim_data *, const int, double *, const double *, const double *);
void deriv_build_AY_k(prim_data *, const int, double *, const double *, const double *);
void deriv_build_AZ_k(prim_data *, const int, double *, const double *, const double *);
void deriv_build_BX_k(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_BY_k(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_BZ_k(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_CX_k(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_CY_k(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_CZ_k(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_DX_k(prim_data *, const int, double *, const double *, const double *);
void deriv_build_DY_k(prim_data *, const int, double *, const double *, const double *);
void deriv_build_DZ_k(prim_data *, const int, double *, const double *, const double *);
void deriv_build_AX_l(prim_data *, const int, double *, const double *, const double *);
void deriv_build_AY_l(prim_data *, const int, double *, const double *, const double *);
void deriv_build_AZ_l(prim_data *, const int, double *, const double *, const double *);
void deriv_build_BX_l(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_BY_l(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_BZ_l(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_CX_l(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_CY_l(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_CZ_l(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_DX_l(prim_data *, const int, double *, const double *, const double *);
void deriv_build_DY_l(prim_data *, const int, double *, const double *, const double *);
void deriv_build_DZ_l(prim_data *, const int, double *, const double *, const double *);
void deriv_build_AX_m(prim_data *, const int, double *, const double *, const double *);
void deriv_build_AY_m(prim_data *, const int, double *, const double *, const double *);
void deriv_build_AZ_m(prim_data *, const int, double *, const double *, const double *);
void deriv_build_BX_m(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_BY_m(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_BZ_m(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_CX_m(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_CY_m(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_CZ_m(prim_data *, const int, const int, double *, const double *, const double *);
void deriv_build_DX_m(prim_data *, const int, double *, const double *, const double *);
void deriv_build_DY_m(prim_data *, const int, double *, const double *, const double *);
void deriv_build_DZ_m(prim_data *, const int, double *, const double *, const double *);
