if(ENABLE_OMP)
    find_package(OpenMP)   
else()
    set(ENABLE_THREADED_MKL FALSE)
endif()

if(OPENMP_FOUND)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")                                              
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")    
    set(ENABLE_THREADED_MKL TRUE)
endif()
