
srcdir = /Users/masaaki/psi4/doc/installation

MAN = installation

include ../MakeVars

TEX = installation.tex

SUBTEX = \

DVI = $(TEX:%.tex=%.dvi)
PS = $(DVI:%.dvi=%.ps)
HTML = $(TEX:%.tex=%.html)

include ../MakeRules
